### PR TITLE
Basic html skeleton

### PR DESCRIPTION
**Pull request by Mlipphardt**
Added html skeleton to file index.html.

### CODE REVIEW

**Comment by cgrady3** [comment]
lkjlj

**Comment by Mlipphardt** [comment]
Below the comments, there should be a 'merge pull request' option, I believe!

**Comment by Erodriz107** [comment]
Edgar was here

**Review by Erodriz107 — COMMENTED** [review]
Test

**Review by Erodriz107 — APPROVED** [review]

**Pull request merged**
